### ISSUE TITLE
Increase font size on map

### ISSUE THREAD

**Issue by jakobkolb** [KilianZimmerer/nama_map#1]
On my screen (PC) the font size on the map is really small. I am afraid many people will have trouble reading it. Would be good to have something like 12pt word equivalent..

**Comment by KilianZimmerer** [comment]
what exactly do you mean by 'on map'?

**Comment by jakobkolb** [comment]
Street names etc. Also don't increase when I zoom into the map but reload and are very small again.

**Comment by KilianZimmerer** [comment]
Done!
