### ISSUE TITLE
Show Data from Google Sheet

### ISSUE THREAD

**Issue by jakobkolb** [KilianZimmerer/nama_map#2]
The actual Info from Shops ist currently at 
https://docs.google.com/spreadsheets/d/1etrMBYqSJtiSRTaoLslWVeregG1GgwU6ZLyFr4GYi5g/edit#gid=654862144

Would be great, If we could show these.

**Comment by KilianZimmerer** [comment]
okay cool, will implement them in the evening

**Comment by KilianZimmerer** [comment]
Done!
